# Generated by Django 4.1.7 on 2023-04-01 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_category_product_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="category", name="product_id",),
        migrations.AddField(
            model_name="product",
            name="category_id",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
